2024-01-10 22:22:31 : root - DEBUG - inside main
2024-01-10 22:22:31 : root - DEBUG - asking question
2024-01-10 22:23:16 : root - DEBUG - inside main
2024-01-10 22:23:16 : root - DEBUG - asking question
2024-01-10 22:24:09 : root - DEBUG - inside main
2024-01-10 22:24:09 : root - DEBUG - asking question
2024-01-10 22:24:14 : root - DEBUG - exiting main
2024-01-10 22:39:43 : root - DEBUG - inside main
2024-01-10 22:39:43 : root - DEBUG - asking question
2024-01-10 22:40:03 : urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): wttr.in:443
2024-01-10 22:40:08 : urllib3.connectionpool - DEBUG - https://wttr.in:443 "GET /Goslar HTTP/1.1" 200 8676
2024-01-10 22:42:05 : root - DEBUG - inside main
2024-01-10 22:42:05 : root - DEBUG - asking question
2024-01-10 22:42:15 : root - DEBUG - exiting main
2024-01-10 22:43:55 : root - DEBUG - inside main
2024-01-10 22:43:55 : root - DEBUG - asking question
2024-01-10 22:44:01 : root - DEBUG - exiting main
2024-01-10 22:45:52 : root - DEBUG - inside main
2024-01-10 22:45:57 : root - DEBUG - exiting main
2024-01-10 22:46:02 : root - DEBUG - inside main
2024-01-10 22:46:02 : root - ERROR - Traceback (most recent call last):
  File "c:\Users\rohit\OneDrive\Desktop\code\ChatBot.py", line 331, in import_qa_from_csv
    raise FileNotFoundError(f"Invalid file path: {file_path}")
FileNotFoundError: Invalid file path: C:\Users\rohit\Downloads\file_path.csvhf

2024-01-10 22:46:02 : root - ERROR - Invalid file path: C:\Users\rohit\Downloads\file_path.csvhf
2024-01-10 22:46:02 : root - DEBUG - exiting main
2024-01-10 22:53:46 : root - DEBUG - inside main
2024-01-10 22:53:46 : root - DEBUG - asking question
2024-01-10 22:53:51 : root - DEBUG - exiting main
2024-01-10 22:53:56 : root - DEBUG - inside main
2024-01-10 22:53:56 : root - DEBUG - asking question
2024-01-10 22:54:00 : root - DEBUG - exiting main
2024-01-10 22:54:04 : root - DEBUG - inside main
2024-01-10 22:54:04 : root - DEBUG - asking question
2024-01-11 11:20:32 : root - DEBUG - inside main
2024-01-11 11:20:32 : root - DEBUG - asking question
2024-01-11 11:25:45 : urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): wttr.in:443
2024-01-11 11:26:15 : root - DEBUG - inside main
2024-01-11 11:26:15 : root - DEBUG - asking question
2024-01-11 11:26:29 : urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): wttr.in:443
2024-01-11 11:27:33 : root - DEBUG - inside main
2024-01-11 11:27:33 : root - DEBUG - asking question
2024-01-11 11:28:06 : root - DEBUG - exiting main
2024-01-11 11:28:09 : root - DEBUG - inside main
2024-01-11 11:28:09 : root - DEBUG - asking question
2024-01-11 11:33:37 : root - DEBUG - inside main
2024-01-11 11:33:37 : root - DEBUG - asking question
2024-01-11 11:33:43 : root - DEBUG - exiting main
2024-01-11 11:33:45 : root - DEBUG - inside main
2024-01-11 11:33:45 : root - DEBUG - asking question
2024-01-11 11:33:56 : urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): wttr.in:443
2024-01-11 11:33:59 : urllib3.connectionpool - DEBUG - https://wttr.in:443 "GET /Wolfenb%C3%BCttel HTTP/1.1" 200 8679
2024-01-11 11:39:34 : root - DEBUG - inside main
2024-01-11 11:39:34 : root - DEBUG - asking question
2024-01-11 11:41:27 : root - DEBUG - inside main
2024-01-11 11:41:27 : root - DEBUG - asking question
2024-01-11 11:43:29 : urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): wttr.in:443
2024-01-11 11:43:29 : urllib3.connectionpool - DEBUG - https://wttr.in:443 "GET /Wolfenb%C3%BCttel HTTP/1.1" 200 8679
